apiVersion: v1
kind: Namespace
metadata:
  name: kakaocloud-library
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: kakaocloud-library
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: client
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: kakaocloud-library
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: server
